config/routes.rb
Blog::Application.routes.draw do
  
  root :to => 'articles#index'
  match '/articles/search/:query' => 'articles#index', :as => 'search'
  resources :articles do
    member do
      post :notify_friend
    end
    resources :comments
  end
  
  resources :users
  
  resource :session
  match '/login' => 'sessions#new', :as => 'login'
  match '/logout' => 'sessions#destroy', :as => 'logout'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :excerpt, :location, :published_at, :title, :category_ids
  
  validates :title, :presence => true
  validates :body, :presence => true
  
  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :comments
  
  scope :published, where("articles.published_at IS NOT NULL")
  scope :draft, where("articles.published_at IS NULL")
  scope :resent, lambda { published.where("articles.published_at > ?", 1.week.ago.to_date) }
  scope :where_title, lambda { |term| where("articles.title LIKE ?", "%#{term}%") }
  
  def long_title
    "#{title} - #{published_at}"
  end
  
  def published?
    published_at.present?
  end
  
  def owned_by?(owner)
    user == owner
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_filter :authenticate, :except => [:index, :show, :notify_friend]
  
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = current_user.articles.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, :notice => I18n.t('articles.create_success') }
        format.json { render :json => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = current_user.articles.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, :notice => I18n.t('articles.update_success') }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
  
  def notify_friend
    @article = Article.find params[:id]
    Notifier.email_friend(@article, params[:name], params[:email]).deliver
    redirect_to @article, :notice => 'Successfully sent a message to your friend'
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<%= div_for article do %>
	<h3>
		<%= link_to article.title, article %>
		<% if article.owned_by? current_user %>
		<span class="actions">
			<%= link_to t('general.edit'), edit_article_path(article) %>
			<%= link_to t('general.delete'), article, :confirm => 'Are you shure?', :method => :delete %>
		</span>
		<% end %>
	</h3>
	<%= simple_format article.body %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label "Categories" %><br />    
    <% for category in Category.all %>
    	<%= check_box_tag "article[category_ids][]", category.id,
    		@article.category_ids.include?(category.id), :id => dom_id(category) %>
    	<%= label_tag dom_id(category), category.name, :class => "check_box_label" %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :excerpt %><br />
    <%= f.text_field :excerpt %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/articles/_notify_friend.html.erb
<%= form_tag(notify_friend_article_path(@article), :id => "notify_friend_form", :style => "display:none") do %>
	<div class="field">
		<%= label_tag :name, "Your name" %>
		<%= text_field_tag :name %>
	</div>
	<div class="field">
		<%= label_tag :email, "Your friend's email" %>
		<%= text_field_tag :email %>
	</div>
	<div class="actions">
		<%= submit_tag "Send" %> or
		<%= link_to "Cancel", "#", :onclick => "$('#notify_friend_form').slideUp()" %>
	</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<div id="articles">
	<%= render @articles %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render @article %>

<%= link_to "Email a friend", "#", :onclick => "$('#notify_friend_form').slideDown()" %>
<%= render "notify_friend" %>

<h3>Comments</h3>
<div id="comments">
	<%= render @article.comments %>
</div>

<%= link_to "new comment", new_article_comment_path(@article, :format => :js), :remote => true, :id => "new_comment_link" %>